version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      pages-and-artifact-actions:
        patterns:
          - "actions/*pages*"
          - "actions/*-artifact"
