services:
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    volumes:
      - .:/workspace:ro
      - ./tests/logs:/tmp/logs
    working_dir: /workspace
# --- test tools ---
  eclint:
    image: mstruebing/editorconfig-checker
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
  makelint:
    image: mrtazz/checkmake
    volumes:
      - ./Makefile:/Makefile:ro
  shellcheck:
    image: koalaman/shellcheck-alpine
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
