name: Scans docker container in ghcr.io
description: |
  This action scan an image in ghcr.io reporting on its vulnerabilities and can upload a sarif result to GitHub.

inputs:
  image-name:
    description: "The full image name excluding ghcr.io/<my_container>"
    required: true
  image-tag:
    description: The image tag
    required: true
  upload-sarif:
    description: Determines if the sarif result is uploaded
    required: true
  grype-category:
    description: The grype category name
    required: false
    default: "grype"

runs:
  using: composite
  steps:
    - name: Resolve container image name
      shell: bash
      run: echo "LOWERCASED=$(echo 'ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@3da7dc6e2b31f99ef2cb9fb4c50fb0971e0d0139
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        ecr: false

    - name: Scan image
      uses: anchore/scan-action@v6
      id: scan
      with:
        image: ${{ env.LOWERCASED }}:${{ inputs.image-tag }}
        fail-build: false
        output-format: sarif
        output-file: results.sarif

    - name: Print scanning summary
      shell: bash
      run: |
        pipx install sarif-tools
        {
          echo \`\`\`
          sarif summary results.sarif
          echo \`\`\`
        } >> $GITHUB_STEP_SUMMARY

    - name: Upload sarif report
      if: ${{ inputs.upload-sarif == 'true' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        category: ${{ inputs.grype-category }}
