name: Update base environment
description: ""

inputs:
  configuration:
    description: The configuration file
    required: false
  configurations:
    description: A newline separated list of configuration files
    required: false
  deploy_key:
    description: A deploy key that has access to the environment repository.
    required: true
  branch:
    description: The branch in the environment repository to target.
    required: true
    default: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'main' || github.event.pull_request.head.ref }}
  repository:
    description: The environment repository
    required: false
    default: ${{ github.repository_owner }}/eo-base-environment
  dry_run:
    description: Perform all actions but without committing changes
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Verify configuration(s)
      shell: bash
      if: inputs.configuration == '' && inputs.configurations == ''
      run: exit 1

    - uses: actions/checkout@v3

    - name: Checkout environment repository
      uses: actions/checkout@v3
      with:
        path: base
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.deploy_key }}
        ref: main

    - name: Use correct branch
      working-directory: base
      shell: bash
      if: ${{ github.ref_name != 'main' }}
      run: git fetch && git checkout ${{ inputs.branch }} 2>/dev/null || git checkout -b ${{ inputs.branch }}

    - name: Resolve version
      uses: Energinet-DataHub/acorn-actions/actions/docker-image-version@v1 # TODO: This seems to be changed

    - name: Update references
      shell: bash
      working-directory: base
      if: inputs.configuration != ''
      run: |
        configuration="../${{ inputs.configuration }}"
        repo=$(yq '.repo' < "$configuration")
        name=$(yq '.name' < "$configuration")

        image="$repo/$name:${{ env.version }}"
        yq -ojson .references < "$configuration" | jq -rc '.[]' | while read -r reference; do
          file=$(jq -r -c '.file' <<< "$reference")
          path=$(jq -r -c '.path' <<< "$reference")
          echo yq -ie "'($path) = \"$image\"'" "$file" | bash -x
        done

    - name: Update multiple references
      shell: bash
      working-directory: base
      if: inputs.configurations != ''
      run: |
        while read file; do
          configuration="../$file"
          repo=$(yq '.repo' < "$configuration")
          name=$(yq '.name' < "$configuration")

          image="$repo/$name:${{ env.version }}"
          yq -ojson .references < "$configuration" | jq -rc '.[]' | while read -r reference; do
            file=$(jq -r -c '.file' <<< "$reference")
            path=$(jq -r -c '.path' <<< "$reference")
            echo yq -ie "'($path) = \"$image\"'" "$file" | bash -x
          done
        done <<< ${{ inputs.configuration }}

    - name: Commit changes
      id: commit
      if: ${{ inputs.dry_run != 'true' }}
      uses: EndBug/add-and-commit@v9
      with:
        message: Use ${{ env.version }}
        new_branch: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'main' || inputs.branch }}
        push: --force-with-lease --set-upstream origin ${{ github.event_name == 'push' && github.ref_name == 'main' && 'main' || inputs.branch }}
        default_author: github_actions
        cwd: base

    - name: Verify changes were pushed
      shell: bash
      if: ${{ inputs.dry_run == 'false' && steps.commit.outputs.pushed == 'false' }}
      run: |
        echo "::error::Nothing was committed or pushed"
        exit 1
