name: Automated release tagging

on:
  release:
    types: [published]

jobs:
  movetag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get major version number and update release tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git tag -fa ${MAJOR} -m "Update major version tag"
          git push origin ${MAJOR} --force
