name: Validate Actions and Workflows

on:
  pull_request:
    paths:
      - .github/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            action-validator 0.5.1
      - name: Lint Actions
        run: |
          find .github/workflows .github/actions -type f \( -iname \*.yaml -o -iname \*.yml \) | xargs -I {} action-validator --verbose {}
